# Benchmark configuration
# Lines starting with # are comments

# SSH connection
SshUser=guser
ClientMachineCount=[61, 25, 25]
ClientMachineHostnames=[vm0.fs8v2client.southcentralus.cloudapp.azure.com, vm0.eps4v6client.southcentralus.cloudapp.azure.com, vm0.dps4v6client.southcentralus.cloudapp.azure.com]
Multiplier=2

# Benchmark parameters
Server=10.5.1.4
Port=7000
Threads=16
Runtime=15
ClusterBench=true

# Use a connection pool for every worker
# If not set to true every benchmark instance wii create a single connection per shard per thread
# e.g shards = 6, threads = 8 => 48 workers/connections
Pool=true
# Broadcast requests across collection pool for every worker and wait for response
Broadcast=false

# Operation type (optional, e.g., GET, SET, MGET, MSET)
Op=GET

# Data parameters
#DbSize=1024
# 7813 * 128 ~ 1,000,000
#DbSize=7813
# 15625*64 ~ 1,000,000
DbSize=15625
#DbSize=18519
#DbSize=166667
#DbSize=1024
#DbSize=32768
#DbSize=262144
#DbSize=1048576
KeyLength=8
ValueLength=100
BatchSize=256

# Additional arguments (optional)
#ExtraArgs=--skipload
