#cloud-config
write_files:
  - path: /etc/profile.d/aliases.sh
    permissions: '0644'
    content: |
      alias ll='ls -la'

runcmd:
  # Install all build dependencies
  - sudo tdnf install -y git vim tar gzip wget curl grep sed make cmake gcc gcc-c++ binutils glibc-devel pkg-config net-tools autoconf automake libtool openssl-devel zlib-devel util-linux-devel icu libxml2-devel jemalloc-devel liburing liburing-devel libaio libaio-devel libevent-devel glibc-devel
  - sudo tdnf install -y kernel-headers glibc-devel gcc-c++
  - sudo tdnf install -y tcpdump pciutils jq iperf3 ethtool powershell

  # Clone AzureBench repo, install scripts, and execute deploy commands from manifest
  - sudo -u guser git clone https://github.com/vazois/AzureBench.git /home/guser/AzureBench
  - sudo pwsh /home/guser/AzureBench/node/update.ps1 -Run